# Generated by Django 4.2 on 2023-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnote1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'OUt for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
