# Generated by Django 4.2 on 2023-06-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnote1', '0005_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
